### ISSUE TITLE
Why does this code add a variable j

### ISSUE THREAD

**Issue by smart6666** [cloudwu/lua-snapshot#18]
Why does this code add a variable j?Can the author help explain?
`int i,j;
		for (j=1;j>-1;j-=2) {
			for (i=j;;i+=j) {
				const char * name = lua_getlocal(cL, &ar, i);
				if (name == NULL)
					break;
				snprintf(tmp, sizeof(tmp), "%s : %s:%d",name,ar.short_src,ar.currentline);
				mark_object(cL, dL, t, tmp);
			}
		}`

**Comment by cloudwu** [comment]
There is a bug.  It should be `j>=-1` .

**Comment by cloudwu** [comment]
https://lua.org/manual/5.4/manual.html#pdf-debug.getlocal

> Negative indices refer to vararg arguments; -1 is the first vararg argument.

**Comment by smart6666** [comment]
Thank you. So this is not going to be changed? Or this seems to have little impact on the test results, right?
